


let inputHTML = document.getElementById('inputHTML')
const codeContainer = document.getElementById('codeSnippet');
let convertedCode = ""
let currentIndex = 0;
var counter = {};
var jsCode
function startProcess() {
  highlightCode()
  codeContainer.innerHTML = '';
  currentIndex = 0;
  counter = {};
  jsCode = '';
  convertedCode = convertHtmlToJs(inputHTML.innerText);
  setTimeout(() => {
    typeCode();
  }, 100);
}

function convertHtmlToJs(html) {
  var parser = new DOMParser();
  var doc = parser.parseFromString(html, "text/html");

  function convertElementToJs(element, indent) {
    var tagName = element.tagName.toLowerCase();
    var variableName = tagName;
    counter[tagName] = counter[tagName] ? counter[tagName] + 1 : 1;
    if (counter[tagName] > 1) {
      variableName += counter[tagName];
    }
    jsCode = "            // Create " + tagName + " element\n";
    jsCode += indent + "var\u0020" + variableName + " = document.createElement('" + tagName + "');\n";

    for (var i = 0; i < element.attributes.length; i++) {
      var attribute = element.attributes[i];
      jsCode += indent + variableName + ".setAttribute('" + attribute.name + "', '" + attribute.value + "');\n";
    }

    if (element.childNodes.length === 1 && element.childNodes[0].nodeType === Node.TEXT_NODE) {
      var textContent = element.textContent.trim();
      if (textContent.length > 0) {
        jsCode += indent + variableName + ".textContent = `" + textContent + "`;\n";
      }

    }

    for (var i = 0; i < element.children.length; i++) {
      var child = element.children[i];
      jsCode += convertElementToJs(child, indent + "  ");
    }

    var parentTagName = element.parentNode.tagName.toLowerCase();
    jsCode += "// Append " + variableName + " to " + parentTagName + "\n";
    if (parentTagName === "body") {
      parentTagName = "document.body"
    }

    jsCode += indent + parentTagName + ".appendChild(" + variableName + ");\n";

    return jsCode;
  }

  var jsCode = convertElementToJs(doc.body.firstChild, "");

  return jsCode + "// Generated By Ranjan";
}


function typeCode() {

  convertedCode = convertedCode.replace(/ {2,}(?!$)|(?<! ) {2,}/g, '')

  if (currentIndex < convertedCode.length) {
    codeContainer.innerHTML += convertedCode.charAt(currentIndex);


    currentIndex++;
    Prism.highlightAll();
    setTimeout(typeCode, 1);
  }
}

let cde = document.querySelector('code')

setTimeout(function() {
  cde.scrollTop = cde.scrollHeight;
}, 0);
// window.addEventListener('keyup',(e)=>{
//   if(e.key ==="Enter"){
//     startProcess()
//   }
// })

let clear = document.getElementById('clr')
let copy = document.getElementById('cpy')
let clrText = document.getElementById('clrText')
let cpyText = document.getElementById('cpyText')
let cpyIcon = document.querySelector('[data-cpy]')
let clrIcon = document.querySelector('[data-clr]')
clear.addEventListener('click', clear1)
copy.addEventListener('click', copyCode)

function clear1() {
  inputHTML.innerHTML = ""
  clrText.innerHTML = "Cleared"
  clrIcon.innerHTML = "check"
  reAddTextAndIcon(clrIcon, "cancel", clrText, "Clear")
}

function copyCode() {
  navigator.clipboard.writeText(document.querySelector('code').innerText)
  cpyIcon.innerHTML = "check"
  cpyText.innerHTML = "Copied"
  reAddTextAndIcon(cpyIcon, "content_copy", cpyText, "Copy code")
}
function reAddTextAndIcon(icon, iconName, elem, text) {
  setTimeout(() => {
    elem.innerHTML = text
    icon.innerHTML = iconName
  }, 3000)
}



inputHTML.addEventListener('paste', () => {
  setTimeout(() => {
    highlightCode()
  }, 30)
})

function highlightCode() {
  const code = inputHTML.innerText;
  inputHTML.innerHTML = Prism.highlight(code, Prism.languages.html);
}


function showInfo() {
  confirm("Made By Ranjan\nkashyapranjan9977@gmail.com")
}
